app:
  host: 127.0.0.1
  port: 8080

auth:
  secret: my_secret_key
  duration: 100000 #second
  hash_cost: 14

DB:
  host: 127.0.0.1
  port: 3306
  user: root
  pass: secret
  name: gateway
  conn_max_lifetime: 30

PMS:
  url: "http://127.0.0.1:8081"
