app:
  host: 127.0.0.1
  port: 8080

auth:
  secret: my_secret_key
  duration: 100 #second
  hash_cost: 14

DB:
  host: 127.0.0.1
  port: 3306
  user: root
  pass: secret
  name: ecom
  conn_max_lifetime: 30